'use strict';
const $=id=>document.getElementById(id);
const SERIES={
 real:{name:'Real GDP level',unit:'Afl. million · constant prices',frequency:'Annual',definition:'The value of output with price changes removed, using the CBS constant-price series.',note:'CBS constant-price series. Figures for 2020–2023 are preliminary. The source table does not explicitly state its price reference year.'},
 nominal:{name:'Nominal GDP level',unit:'Afl. million · current prices',frequency:'Annual',definition:'The value of goods and services produced in Aruba, measured at each year’s prices.',note:'GDP at market prices. Figures for 2020–2023 are preliminary.'},
 growth:{name:'Real GDP growth',unit:'% change from the previous year',frequency:'Annual',definition:'The annual change in inflation-adjusted GDP. Negative values indicate a contraction in output.',note:'Growth rates published by CBS. Figures for 2020–2023 are preliminary. The 2013 growth rate is not supplied in this series.'},
 inflation:{name:'Inflation · year over year',unit:'% change from the same month a year earlier',frequency:'Monthly',definition:'The percentage change in the consumer price index compared with the same month of the previous year.',note:'CBS reported end-of-period inflation, comparing each month with the same month one year earlier.'},
 cpi:{name:'Consumer price index',unit:'Index · June 2019 = 100',frequency:'Monthly',definition:'The price level of a representative basket of household goods and services. This is an index level, not an inflation rate.',note:'All items, total population. Values are from the CBS 2026 monthly reports.'},
 monthly:{name:'Inflation · month over month',unit:'% change from the previous month',frequency:'Monthly',definition:'The change in consumer prices from one month to the next. These monthly rates are not annualized.',note:'Published, rounded monthly changes from CBS. These can differ slightly from rates calculated using the rounded CPI levels.'}
};

const gdpKeys=['real','nominal','growth'];
const outlookNote='CBS history through 2023 (2020–2023 preliminary); CBA September 2026 baseline outlook for 2024–2027. e = estimate; f = forecast.';
SERIES.real.note=outlookNote+' 2025 level is published by CBA. 2024 level is back-calculated from 2025 using 6.3% growth; 2026–2027 levels apply forecast growth of 3.7% and 2.3%. Derived levels are approximate because growth rates are rounded. Price reference year is not stated in the source.';
SERIES.real.definition='Inflation-adjusted output. Historical CBS levels are extended using CBA estimates and baseline forecasts.';
SERIES.nominal.note=outlookNote+' 2025 level is published by CBA. 2024 level is back-calculated using 9.0% nominal growth; 2026–2027 levels apply 4.8% annual nominal growth. Derived levels are approximate.';
SERIES.growth.note=outlookNote+' Published CBA rates: 2024e 5.5%, 2025e 6.3%, 2026f 3.7%, 2027f 2.3%. The 2013 rate is not supplied.';
const cbaMonthly='CBA Monthly Tables, July 2026 (updated 31 August), table ';
Object.assign(SERIES,{
 gdpPerCapita:{name:'GDP per capita · US dollars',unit:'US$ per person · current prices',frequency:'Annual',periods:[2025],definition:'Estimated nominal GDP per resident, converted to US dollars at the official exchange-rate parity.',note:'2025 estimate, calculated: Afl. 7,912.1 million ÷ 1.79 Afl. per US$ ÷ 109,435 residents = US$40,390.80. GDP: CBA September 2026 outlook. Population: CBS end-Q2 2025, used as a midyear proxy rather than a full-year average. Market exchange-rate conversion; not PPP-adjusted and not household income.'},
 reserves:{name:'International reserves',unit:'Afl. million · end of month',frequency:'Monthly',periods:DATA.reserveMonths,definition:'Combined net foreign assets of the CBA and commercial banks, including gold and foreign-exchange revaluation differences.',note:'CBA Monthly Tables December 2024 and July 2026, table 4, column 8. This is the total international-reserves measure, not the CBA-only gross reserve stock.'},
 coverage:{name:'Current-account payment coverage',unit:'Months of current-account payments',frequency:'Annual',periods:DATA.coverageYears,definition:'Year-end international reserves divided by average monthly current-account payments in the same calendar year.',note:'Calculated as 12 × year-end reserves ÷ annual total current-account debits. Includes goods, services, primary income and secondary income. CBA Monthly Tables July 2026, table 4, and External Sector Tables Q4 2025, table 8.2. Latest matched year: 2025; no 2026 payment assumptions are used.'},
 payments:{name:'Current-account payments',unit:'Afl. million · annual debits',frequency:'Annual',periods:DATA.coverageYears,definition:'Payments to non-residents for goods, services, primary income and secondary income in the balance of payments.',note:'CBA External Sector Tables Q4 2025 (15 May 2026), table 8.2, total current-account debits. These annual flows form the denominator of the coverage calculation.'},
 creditAnnual:{name:'Private-sector credit growth · annual',unit:'% change · December over December',frequency:'Annual',periods:DATA.creditYears,definition:'Annual growth in outstanding claims on the private sector, using December balances.',note:cbaMonthly+'1. Calculated from the published 2022–2025 year-end balances; nominal growth, not adjusted for inflation.'}
});
for(const [key,name] of Object.entries({credit:'Private-sector credit',enterprise:'Enterprise credit',consumer:'Consumer credit',housing:'Housing mortgages'})){
 SERIES[key]={name:name+' growth',unit:'% change from the same month a year earlier',frequency:'Monthly',periods:DATA.creditMonths,definition:'Year-over-year growth in outstanding '+name.toLowerCase()+'. This measures credit balances, not new loan issuance.',note:cbaMonthly+'1. Calculated as (balance ÷ same-month prior-year balance − 1) × 100. February–July 2026: the latest six available months, using April and July 2026 table 1 releases. Nominal, not inflation-adjusted.'};
}
Object.assign(SERIES,{
 stayover:{name:'Stay-over visitor arrivals',unit:'Visitors · monthly arrivals',frequency:'Monthly',periods:DATA.tourismMonths,definition:'Visitors who stay overnight in Aruba. Cruise visitors are excluded.',note:'ATA Monthly Reports, January–July 2026, monthly arrivals tables. Counts are visits, not unique people across months.'},
 stayoverGrowth:{name:'Stay-over visitor growth',unit:'% change from the same month a year earlier',frequency:'Monthly',periods:DATA.tourismMonths,definition:'Growth in monthly stay-over arrivals compared with the same month of 2025.',note:'Calculated from ATA Monthly Reports January–July 2026: (2026 arrivals ÷ same-month 2025 arrivals − 1) × 100. Not seasonally adjusted. July: 160,858 versus 141,904 visitors.'}
});
function statusFor(key,period){if(key==='gdpPerCapita')return '2025 estimate · calculated';if(key==='stayoverGrowth')return 'Calculated from ATA data';if(gdpKeys.includes(key))return period>=2026?'Forecast'+(key==='growth'?'':' · derived level'):period>=2024?'Estimate'+(period===2024&&key!=='growth'?' · derived level':''):period>=2020?'Preliminary':'Published';return ['coverage','creditAnnual','credit','enterprise','consumer','housing'].includes(key)?'Calculated from CBA data':'Published';}
function pointLabel(key,p){return dateLabel(p)+(gdpKeys.includes(key)&&p>=2024?(p<=2025?'e':'f'):'');}
const palette=['#0c7465','#4e9683','#90b59a','#b8caaa','#dfcf96','#b49a6e','#8d9c85','#cad4c4'];
let state={indicator:'real',style:'line',start:0,end:14,year:2023,all:false};
const periods=()=>SERIES[state.indicator].periods|| (SERIES[state.indicator].frequency==='Annual'?DATA.years:DATA.months);
const fmt=(v,d=1)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const dateLabel=p=>String(p).includes('-')?new Date(p+'-02T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'}):String(p);
function setIndicator(key){if(!SERIES[key])throw new Error('Unknown indicator');state.indicator=key;state.start=0;state.end=periods().length-1;$('indicator').value=key;updatePeriods();render();}
function updatePeriods(){const opts=periods().map((p,i)=>`<option value="${i}">${dateLabel(p)}</option>`).join('');$('start').innerHTML=opts;$('end').innerHTML=opts;$('start').value=state.start;$('end').value=state.end;}
function selected(){return periods().map((p,i)=>({period:p,value:DATA[state.indicator][i],status:statusFor(state.indicator,p)})).slice(state.start,state.end+1);}
function render(){const meta=SERIES[state.indicator],rows=selected();$('chart-title').textContent=meta.name;$('chart-unit').textContent=meta.unit;$('frequency').textContent=meta.frequency;$('definition').textContent=meta.definition;$('chart-note').textContent=meta.note;$('chart-legend').textContent=gdpKeys.includes(state.indicator)?'● Historical   ● Estimate (e)   ┄ Forecast (f)':meta.name;$('chart-period').textContent=dateLabel(rows[0].period)+' – '+dateLabel(rows.at(-1).period);$('table-unit').textContent=meta.unit;$('line').setAttribute('aria-pressed',state.style==='line');$('bar').setAttribute('aria-pressed',state.style==='bar');$('table-body').innerHTML=rows.map(r=>`<tr><td>${dateLabel(r.period)}</td><td>${r.value===null?'Not available':fmt(r.value,state.indicator==='cpi'?2:1)}</td><td>${r.value===null?'Not available':r.status}</td></tr>`).join('');drawChart(rows,meta);$('tooltip').hidden=true;}
function drawChart(rows,meta){const W=840,H=280,L=62,R=23,T=22,B=36;const vals=rows.map(r=>r.value).filter(v=>v!==null);if(!vals.length){$('chart').innerHTML='<p>No verified observations in this period. Select a wider range.</p>';return;}let lo=Math.min(...vals),hi=Math.max(...vals);const pad=(hi-lo||Math.abs(hi)||1)*.18;lo-=pad;hi+=pad;if(state.style==='bar'||['growth','inflation','monthly'].includes(state.indicator)){lo=Math.min(0,lo);hi=Math.max(0,hi);}const x=i=>state.style==='bar'?L+(W-L-R)*(i+.5)/rows.length:L+(W-L-R)*(rows.length===1?.5:i/(rows.length-1));const y=v=>T+(hi-v)/(hi-lo)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${meta.name}, ${$('chart-period').textContent}. Exact values are available in View chart data.">`;
 for(let j=0;j<5;j++){const v=lo+(hi-lo)*j/4,py=y(v);svg+=`<line x1="${L}" y1="${py}" x2="${W-R}" y2="${py}" stroke="#e8eee6" stroke-dasharray="3 4"/><text x="${L-12}" y="${py+4}" text-anchor="end">${fmt(v,state.indicator==='cpi'?1:(hi-lo>100?0:1))}</text>`;}
 if(lo<0&&hi>0)svg+=`<line x1="${L}" y1="${y(0)}" x2="${W-R}" y2="${y(0)}" stroke="#b1c5b8"/>`;
 if(gdpKeys.includes(state.indicator)){for(const [from,to,color,label] of [[2024,2025,'#edf3ed','Estimates'],[2026,2027,'#f6efdf','Forecasts']]){const inds=rows.map((r,i)=>r.period>=from&&r.period<=to?i:-1).filter(i=>i>=0);if(inds.length){const gap=(W-L-R)/Math.max(1,state.style==='bar'?rows.length:rows.length-1),left=Math.max(L,x(inds[0])-gap/2),right=Math.min(W-R,x(inds.at(-1))+gap/2);svg+=`<rect x="${left}" y="${T}" width="${right-left}" height="${H-T-B}" fill="${color}" opacity=".7"/><text x="${(left+right)/2}" y="${T+14}" text-anchor="middle">${label}</text>`;}}}
 if(state.style==='line'){rows.forEach((r,i)=>{if(!i||r.value===null||rows[i-1].value===null)return;const forecast=gdpKeys.includes(state.indicator)&&r.period>=2026,estimate=gdpKeys.includes(state.indicator)&&r.period>=2024;svg+=`<path d="M${x(i-1)},${y(rows[i-1].value)} L${x(i)},${y(r.value)}" fill="none" stroke="${forecast?'#9a6b25':estimate?'#588875':'#0b7568'}" stroke-width="3" ${forecast?'stroke-dasharray="7 5"':''}/>`;});}
 const step=Math.max(1,Math.ceil(rows.length/7));rows.forEach((r,i)=>{const px=x(i);if(i%step===0||i===rows.length-1||(gdpKeys.includes(state.indicator)&&r.period>=2024)){const text=meta.frequency==='Monthly'?dateLabel(r.period).replace('20','’'):pointLabel(state.indicator,r.period);svg+=`<text x="${px}" y="${H-10}" text-anchor="middle">${text}</text>`;}if(r.value===null)return;const py=y(r.value);if(state.style==='bar'){const bw=Math.min(40,(W-L-R)/rows.length*.55);svg+=`<rect x="${px-bw/2}" y="${Math.min(py,y(0))}" width="${bw}" height="${Math.max(1,Math.abs(y(0)-py))}" fill="${gdpKeys.includes(state.indicator)&&r.period>=2026?'#b79762':r.value<0?'#b79762':'#0b7568'}" rx="3"/>`;}else svg+=`<circle cx="${px}" cy="${py}" r="4" fill="white" stroke="#0b7568" stroke-width="2"/>`;svg+=`<circle class="datum" data-i="${i}" cx="${px}" cy="${py}" r="14" fill="transparent" tabindex="0" role="graphics-symbol" aria-label="${dateLabel(r.period)}: ${fmt(r.value,2)}, ${meta.unit}"/>`;});svg+='</svg>';$('chart').innerHTML=svg;document.querySelectorAll('.datum').forEach(el=>{function show(e){const r=rows[+el.dataset.i],tip=$('tooltip');tip.innerHTML=`${dateLabel(r.period)}<b>${fmt(r.value,state.indicator==='cpi'?2:1)}${['growth','inflation','monthly'].includes(state.indicator)?'%':''}</b>${meta.unit}<br>${r.status}`;tip.hidden=false;const rect=el.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(window.innerWidth-280,e.clientX||rect.left+10))+'px';tip.style.top=Math.max(8,Math.min(window.innerHeight-tip.offsetHeight-10,(e.clientY||rect.top)-80))+'px';}el.addEventListener('pointerenter',show);el.addEventListener('pointermove',show);el.addEventListener('focus',show);el.addEventListener('pointerleave',()=>$('tooltip').hidden=true);el.addEventListener('blur',()=>$('tooltip').hidden=true);});}
const shortNames={'Accommodation and food service activities':'Accommodation & food services','Wholesale and retail trade; Repair of motor vehicles and motorcycles':'Wholesale & retail trade','Public administration and defence; Compulsory social security':'Public administration','Financial and insurance activities':'Finance & insurance','Electricity, gas, steam and air conditioning supply/Water supply; sewerage, waste management and remediation activities':'Utilities & waste management','Human health and social work activities':'Health & social work','Administrative and support service activities':'Administrative & support services','Professional, scientific and technical activities':'Professional & technical services','Agriculture, forestry and fishing; mining and quarrying':'Agriculture, fishing & mining'};
function renderIndustries(){const i=state.year-2013,total=DATA.nominal[i];let arr=DATA.industries.map(s=>({name:shortNames[s.name]||s.name,value:s.values[i]}));arr.push({name:'Taxes less subsidies on products',value:DATA.taxes[i]});arr.sort((a,b)=>b.value-a.value);const display=state.all?arr:[...arr.slice(0,6),{name:'Other industries',value:arr.slice(6).reduce((s,r)=>s+r.value,0)}];$('composition-total').textContent='Afl. '+fmt(total/1000,2)+' billion';$('composition-status').textContent=state.year>=2020?'Preliminary':'Published';$('stacked').innerHTML=display.map((s,j)=>`<span style="width:${s.value/total*100}%;background:${palette[j%palette.length]}" title="${s.name}: ${fmt(s.value/total*100)}%"></span>`).join('');$('industry-bars').innerHTML=display.map((s,j)=>`<div class="industry-row"><div><span class="industry-name"><i style="background:${palette[j%palette.length]}"></i>${s.name}</span><div class="industry-track"><span style="width:${s.value/total*100}%;background:${palette[j%palette.length]}"></span></div></div><strong title="Afl. ${fmt(s.value,2)} million">${fmt(s.value/total*100)}%</strong></div>`).join('');$('all-industries').textContent=state.all?'Show fewer industries ↑':'Show all industries ↓';$('all-industries').setAttribute('aria-expanded',state.all);}
function renderPrices(){const items=[['Transport',8.4],['Communications',4.9],['Restaurants & hotels',4.8],['Food & non-alcoholic drinks',3.5],['Housing',1.2],['Health',-1.8],['Household operation',-7.1]];$('price-bars').innerHTML=items.map(([name,value])=>`<div class="price-row"><span>${name}</span><div class="price-track" aria-hidden="true"><span class="${value<0?'negative':''}" style="left:${value<0?50-Math.abs(value)/9*50:50}%;width:${Math.abs(value)/9*50}%"></span></div><strong>${value>0?'+':''}${fmt(value)}%</strong></div>`).join('');}
$('indicator').innerHTML=Object.entries(SERIES).map(([key,m])=>`<option value="${key}">${m.name}</option>`).join('');
$('indicator').addEventListener('change',e=>setIndicator(e.target.value));$('start').addEventListener('change',e=>{state.start=+e.target.value;if(state.start>state.end){state.end=state.start;$('end').value=state.end;}render();});$('end').addEventListener('change',e=>{state.end=+e.target.value;if(state.end<state.start){state.start=state.end;$('start').value=state.start;}render();});['line','bar'].forEach(style=>$(style).addEventListener('click',()=>{state.style=style;render();}));$('reset').addEventListener('click',()=>{state.style='line';setIndicator('real');});document.querySelectorAll('[data-series]').forEach(b=>b.addEventListener('click',()=>{setIndicator(b.dataset.series);$('explorer').scrollIntoView({behavior:'smooth'});}));$('industry-year').innerHTML=DATA.compositionYears.slice().reverse().map(y=>`<option>${y}</option>`).join('');$('industry-year').addEventListener('change',e=>{state.year=+e.target.value;renderIndustries();});$('all-industries').addEventListener('click',()=>{state.all=!state.all;renderIndustries();});window.addEventListener('scroll',()=>$('tooltip').hidden=true,{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('tooltip').hidden=true;});updatePeriods();render();renderIndustries();renderPrices();

if(document.modelContext?.registerTool){
 const lifetime=new AbortController();
 Promise.resolve(document.modelContext.registerTool({name:'configure_economic_chart',title:'Configure economic chart',description:'Select an Aruba economic indicator and chart style, then return its visible observations.',inputSchema:{type:'object',properties:{indicator:{type:'string',enum:Object.keys(SERIES)},style:{type:'string',enum:['line','bar']}},required:['indicator'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!SERIES[input.indicator]||input.style&&!['line','bar'].includes(input.style))throw new Error('Invalid indicator or chart style');state.style=input.style||'line';setIndicator(input.indicator);return {indicator:state.indicator,style:state.style,unit:SERIES[state.indicator].unit,observations:selected()};}},{signal:lifetime.signal})).catch(()=>{});
 window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
}

function miniChart(id,key,bar=false){
 const meta=SERIES[key],ps=meta.periods,vs=DATA[key],W=520,H=225,L=52,R=25,T=20,B=42;
 const max=Math.max(...vs)*1.12,x=i=>L+(W-L-R)*(i+.5)/vs.length,y=v=>H-B-v/max*(H-T-B);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${meta.name}. ${meta.unit}. Select Explore for data table and chart controls.">`;
 for(let j=0;j<=3;j++){let v=max*j/3;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e1e8df"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,max>100?0:1)}</text>`;}
 if(!bar)svg+=`<path d="${vs.map((v,i)=>(i?'L':'M')+x(i)+','+y(v)).join(' ')}" fill="none" stroke="#0b7568" stroke-width="3"/>`;
 vs.forEach((v,i)=>{let label=typeof ps[i]==='number'?ps[i]:dateLabel(ps[i]).replace('20','’');svg+=bar?`<rect x="${x(i)-24}" y="${y(v)}" width="48" height="${H-B-y(v)}" rx="3" fill="#0b7568"><title>${label}: ${fmt(v,2)} ${meta.unit}</title></rect><text x="${x(i)}" y="${y(v)-8}" text-anchor="middle">${fmt(v)}</text>`:`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#0b7568"><title>${label}: ${fmt(v,2)} ${meta.unit}</title></circle>`;if(i%Math.max(1,Math.ceil(vs.length/4))===0||i===vs.length-1)svg+=`<text x="${x(i)}" y="${H-16}" text-anchor="middle">${label}</text>`;});
 $(id).innerHTML=svg+'</svg>';
}
miniChart('reserve-mini','reserves');miniChart('coverage-mini','coverage',true);miniChart('credit-mini','credit');miniChart('annual-credit-mini','creditAnnual',true);
$('credit-category').innerHTML=['enterprise','consumer','housing'].map(k=>`<button class="credit-row" data-credit="${k}"><span>${SERIES[k].name.replace(' growth','')}</span><span class="credit-track"><i style="width:${DATA[k].at(-1)/25*100}%"></i></span><strong>${fmt(DATA[k].at(-1))}%</strong></button>`).join('');
document.querySelectorAll('[data-credit]').forEach(b=>b.addEventListener('click',()=>{setIndicator(b.dataset.credit);$('explorer').scrollIntoView({behavior:'smooth'});}));

miniChart('tourism-growth-mini','stayoverGrowth',true);
function renderTourism(){
 const ytd=$('tourism-period').value==='ytd',period=ytd?'January–July 2026':'July 2026',idx=ytd?1:2,total=ytd?1006359:160858;
 $('tourism-total').textContent=fmt(total,0);$('tourism-total-period').textContent=period;
 $('tourism-total-growth').textContent='+'+fmt((total/(ytd?904260:141904)-1)*100)+'% vs. '+(ytd?'January–July 2025':'July 2025');
 const all=DATA.tourismCountries.map(r=>({name:r[0],value:r[idx]})).sort((a,b)=>b.value-a.value);
 const named=all.filter(r=>!['Other South America','Other Europe','Rest of world'].includes(r.name));
 const top=named.slice(0,7),remainder=total-top.reduce((sum,r)=>sum+r.value,0);
 $('tourism-market-period').textContent=period;
 const bars=[...top,{name:'All other markets',value:remainder}];
 $('tourism-country-bars').innerHTML=bars.map((r,i)=>`<div class="tourism-bar"><div><span>${r.name}</span><strong>${fmt(r.value/total*100)}%</strong></div><div class="tourism-track"><i style="width:${r.value/total*100}%;background:${palette[i%palette.length]}"></i></div><small>${fmt(r.value,0)} visitors</small></div>`).join('');
 $('tourism-country-table').innerHTML=all.map(r=>`<tr><td>${r.name}</td><td>${fmt(r.value,0)}</td><td>${fmt(r.value/total*100,2)}%</td></tr>`).join('')+`<tr><th>Total</th><td>${fmt(total,0)}</td><td>100%</td></tr>`;
 const basis=$('stay-basis').value,values=DATA.tourismAccommodation[ytd?'ytd':'month'][basis],sum=values.reduce((a,b)=>a+b,0),names=['Hotels · European plan (EP)','Hotels · all-inclusive','Timeshare','Other accommodation'];
 $('tourism-stay-period').textContent=period+' · '+(basis==='arrivals'?'share of visitors':'share of visitor nights');
 $('tourism-stay-total').textContent=fmt(sum,0)+' '+(basis==='arrivals'?'visitors':'visitor nights');
 $('tourism-stacked').innerHTML=values.map((v,i)=>`<span style="width:${v/sum*100}%;background:${palette[i]}" title="${names[i]}: ${fmt(v/sum*100)}%"></span>`).join('');
 $('tourism-stay-bars').innerHTML=values.map((v,i)=>`<div class="tourism-bar"><div><span>${names[i]}</span><strong>${fmt(v/sum*100)}%</strong></div><div class="tourism-track"><i style="width:${v/sum*100}%;background:${palette[i]}"></i></div><small>${fmt(v,0)} ${basis==='arrivals'?'visitors':'nights'}</small></div>`).join('');
}
$('tourism-period').addEventListener('change',renderTourism);$('stay-basis').addEventListener('change',renderTourism);renderTourism();
